repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: check-yaml
          exclude: docs
        - id: end-of-file-fixer
          types: [ python ]
        - id: trailing-whitespace
        - id: pretty-format-json
          args: [--autofix, --no-sort-keys]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: poetry run ruff format
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [ python, pyi ]
  - repo: https://github.com/myint/autoflake
    rev: v2.1.1
    hooks:
        - id: autoflake
          args:
            - --expand-star-imports
            - --ignore-init-module-imports
            - --in-place
            - --remove-all-unused-imports
            - --remove-duplicate-keys
            - --remove-unused-variables
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: poetry run ruff check
        types: [ python ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [ "--profile", "black", "--skip", "__init__.py", "--filter-files" ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        verbose: true
        entry: bash -c 'make mypy || true' --
        files: domain_matcher
        pass_filenames: false
